# Generated by Django 4.1.3 on 2022-12-31 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFamilia',
            fields=[
                ('idFamilia', models.AutoField(primary_key=True, serialize=False)),
                ('familia', models.CharField(max_length=50)),
                ('antiguedad', models.CharField(max_length=50)),
                ('profesionFamilia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DatosPersonaje',
            fields=[
                ('idPersonaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('altura', models.FloatField()),
                ('peso', models.IntegerField()),
                ('usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DatosProfesion',
            fields=[
                ('idProfesion', models.AutoField(primary_key=True, serialize=False)),
                ('profesion', models.CharField(max_length=50)),
                ('expertis', models.CharField(max_length=50)),
                ('renombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Relacion_personaje_profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPersonaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonajesApp.datospersonaje')),
                ('idProfesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonajesApp.datosprofesion')),
            ],
        ),
        migrations.CreateModel(
            name='Relacion_personaje_familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFamilia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonajesApp.datosfamilia')),
                ('idPersonaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonajesApp.datospersonaje')),
            ],
        ),
    ]
