# Generated by Django 4.1.3 on 2022-11-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonajesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('raza', models.CharField(blank=True, choices=[('Humanos', 'Humanos'), ('Orcos', 'Orcos'), ('Elfos', 'Elfos'), ('Medianos', 'Medianos'), ('Goblins', 'Goblins'), ('Trolls', 'Trolls'), ('Enanos', 'Enanos')], max_length=50, null=True)),
                ('edad', models.IntegerField()),
                ('altura', models.FloatField()),
                ('peso', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='DatosPersonales',
        ),
    ]
