# Generated by Django 4.1.3 on 2023-01-04 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PersonajesApp', '0002_historiapersonaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarPersonaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatarPersonaje', models.ImageField(blank=True, null=True, upload_to='avataresPersonajes')),
                ('idPersonaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonajesApp.datospersonaje')),
            ],
        ),
    ]
